version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      FRONTEND_PORT: 4200
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
#    environment:
#      API_URL: http://backend:8080/api

